Repository phpservermon/phpservermon, pull requests merged in 2019-12, with the labels that each got.

#821 Ukrainian translation
  docs/credits.rst
  src/lang/uk_UA.lang.php
Labels: Needs review

#825 Fix Server Downtime is displayed incorrectly
  src/psm/Util/Server/Updater/StatusUpdater.php
Labels: Status: review needed

#618 Add Traditional Chinese Language File.
  src/lang/zh_TW.lang.php
Labels: Status: changes requested
