Repository phpservermon/phpservermon, pull requests merged in 2020-05, with the labels that each got.

#918 Display time in ms instead of seconds
  src/lang/bg_BG.lang.php
  src/lang/ca_ES.lang.php
  src/lang/cs_CZ.lang.php
  src/lang/da_DK.lang.php
  src/lang/de_DE.lang.php
  src/lang/en_US.lang.php
  src/lang/es_ES.lang.php
  src/lang/et_ET.lang.php
  src/lang/fa_IR.lang.php
  src/lang/fi_FI.lang.php
  src/lang/fr_FR.lang.php
  src/lang/it_IT.lang.php
  src/lang/ja_JP.lang.php
  src/lang/nl_NL.lang.php
  src/lang/no_NB.lang.php
  src/lang/pl_PL.lang.php
  src/lang/pt_BR.lang.php
  src/lang/ru_RU.lang.php
  src/lang/sk_SK.lang.php
  src/lang/sl_SI.lang.php
  src/lang/sv_SE.lang.php
  src/lang/tr_TR.lang.php
  src/lang/uk_UA.lang.php
  src/lang/vi_VN.lang.php
  src/lang/zh_CN.lang.php
  src/lang/zh_TW.lang.php
  src/psm/Module/Config/Controller/ConfigController.php
  src/psm/Module/Server/Controller/AbstractServerController.php
  src/psm/Module/Server/Controller/ServerController.php
  src/psm/Util/Server/HistoryGraph.php
  src/templates/default/module/server/history.tpl.html
  src/templates/default/module/server/server/list.tpl.html
  src/templates/default/module/server/server/view.tpl.html
  src/templates/default/module/server/status/index.tpl.html
Labels: Status: review needed, Type: Feature

#875 Better fit for bigger screens
  src/templates/default/main/body.tpl.html
  src/templates/default/module/server/server/view.tpl.html
  src/templates/default/module/server/status/index.tpl.html
  src/templates/default/static/css/style.min.css
  src/templates/default/static/css/style.min.css.map
  src/templates/default/static/scss/style.scss
Labels: Status: review needed

#919 Updated ping check
  src/psm/Util/Server/Updater/StatusUpdater.php
Labels: Status: review needed, Type: bug

#936 Changed ping6 to ping -6 for windows
  src/psm/Util/Server/Updater/StatusUpdater.php
Labels: Status: review needed, Type: bug

#926 Ability to pan & zoom on charts
  docs/credits.rst
  src/templates/default/module/server/history.tpl.html
  src/templates/default/static/plugin/chartjs/plugin-zoom.min.js
  src/templates/default/static/plugin/hammer/hammer.min.js
  src/templates/default/static/plugin/hammer/hammer.min.js.map
Labels: Type: Feature
